# Generated by Django 3.0.5 on 2020-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryConfirmedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(max_length=120)),
                ('c2', models.CharField(max_length=120)),
                ('c3', models.CharField(max_length=120)),
                ('c4', models.CharField(max_length=120)),
                ('c5', models.CharField(max_length=120)),
            ],
        ),
    ]
