# Generated by Django 3.0.4 on 2020-03-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedata',
            name='recovered',
        ),
    ]
