# Generated by Django 3.0.4 on 2020-03-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_livedata_recovered'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='recovered',
            field=models.CharField(default='-', max_length=120),
        ),
    ]
