# Generated by Django 3.0.4 on 2020-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_livedata_recovered'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('dead', models.CharField(max_length=120)),
                ('confirmed', models.CharField(max_length=120)),
                ('recovered', models.CharField(default='-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='deaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('dead', models.CharField(max_length=120)),
                ('confirmed', models.CharField(max_length=120)),
                ('recovered', models.CharField(default='-', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='recovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TimeField()),
                ('dead', models.CharField(max_length=120)),
                ('confirmed', models.CharField(max_length=120)),
                ('recovered', models.CharField(default='-', max_length=120)),
            ],
        ),
    ]
