# Generated by Django 3.0.4 on 2020-04-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_confirmed_deaths_recovered'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='confirmed',
            new_name='GlobalStats',
        ),
        migrations.DeleteModel(
            name='deaths',
        ),
        migrations.DeleteModel(
            name='recovered',
        ),
    ]
