# Generated by Django 3.0.4 on 2020-04-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20200406_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalstats',
            name='date',
        ),
    ]
