# Generated by Django 3.0.4 on 2020-04-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_globalstats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalstats',
            name='date',
            field=models.CharField(default='', max_length=120),
        ),
    ]
