# Generated by Django 3.0.5 on 2020-04-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_countryconfirmedhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryConfirmedHistory',
        ),
    ]
